### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by benmccann** [richardwilly98/elasticsearch-river-mongodb#510]
@richardwilly98 think you could cut a new release?

There was another fix for MongoDB 3.0 that we should release

https://github.com/richardwilly98/elasticsearch-river-mongodb/commit/51bd235f7910cd01875604e89e2ba893f6425c28

Thanks!

**Comment by richardwilly98** [comment]
I will cut a new release this week-end.

**Comment by richardwilly98** [comment]
Release ```2.0.8``` is available.

**Comment by benmccann** [comment]
Thank you!

**Comment by benmccann** [comment]
@richardwilly98 I only see 2.0.7 as available. Are you sure 2.0.8 was published?

https://search.maven.org/#search%7Cga%7C1%7Celasticsearch-river-mongodb

**Comment by podung** [comment]
+1 I cannot retrieve 2.0.8.  The latest available is 2.0.7

**Comment by richardwilly98** [comment]
I had a checksum validation issue in Sonatype repo. So I just released 2.0.9.

Sorry about that.

**Comment by benmccann** [comment]
@richardwilly98 i don't think it worked yet. i still can't find it on maven central

**Comment by richardwilly98** [comment]
I was able to install it using plugin command.

https://oss.sonatype.org/content/repositories/releases/com/github/richardwilly98/elasticsearch/elasticsearch-river-mongodb/2.0.9/

**Comment by benmccann** [comment]
Yep, I see it now. Looks like it just took awhile for their search index to update. Thanks!

**Comment by podung** [comment]
Thanks
